/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : SCI3.C
**     Project   : Config
**     Processor : MC9S08JM16CGT
**     Component : Init_SCI
**     Version   : Component 01.132, Driver 01.18, CPU db: 3.00.045
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 08/07/2015, 08:55 p.m.
**     Abstract  :
**          This bean encapsulates Serial Communications Interface module
**          This modules allows asynchronous communications with peripheral
**          devices and other microcontroller units (MCU).
**     Settings  :
**          Bean name                                      : SCI3
**          Device                                         : SCI1
**          Settings
**            Baud rate divisor                            : 104
**            Baud rate                                    : 9615.385 baud
**            Loop mode                                    : Disabled
**            Receiver source select                       : Loop mode
**            TxD1 pin direction                           : Output
**            Data Format                                  : 8 bits
**            Stop in Wait mode                            : Disabled
**            Wake up                                      : Idle line wakeup
**            Idle character counting                      : After start bit
**            Parity                                       : None
**            Send break                                   : Disabled
**          Pins
**            RxD pin allocation                           : Enabled
**            RxD pin                                      : PTE1_RxD1
**            RxD pin signal                               : 
**            TxD pin                                      : PTE0_TxD1
**            TxD pin signal                               : 
**          Interrupts
**            Tx interrupt
**              Interrupt                                  : Vsci1tx
**              Transmit interrupt                         : Disabled
**              Transmition complete interrupt             : Enabled
**              ISR name                                   : hola
**            Rx interrupt                                 : 
**              Interrupt                                  : Vsci1rx
**              Receive interrupt                          : Enabled
**              Idle line interrupt                        : Disabled
**              ISR name                                   : tx
**            Error interrupt                              : 
**              Interrupt                                  : Vsci1err
**              Receive framing error interrupt            : Enabled
**              Receive noise error interrupt              : Enabled
**              Receive overrun interrupt                  : Enabled
**              Receive parity error interrupt             : Enabled
**              ISR name                                   : TX
**          Initialization                                 : 
**            Call Init in CPU init. code                  : yes
**            Transmitter                                  : Disabled
**            Receiver                                     : Disabled
**     Contents  :
**         Init - void SCI3_Init(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE SCI3. */

#include "SCI3.h"

/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      Config.c
**      Events.c
**
** ###################################################################
ISR( hola)
{
  // NOTE: The routine should include the following actions to obtain
  //       correct functionality of the hardware.
  //
  // Transmit interrupt flag is cleared by reading the SCI status register
  // and then writing to the SCI data register.
  // Example: Status = SCI1S1;
  //          SCI1D = Data;

}

ISR( tx)
{
  // NOTE: The routine should include the following actions to obtain
  //       correct functionality of the hardware.
  // Receive and idle interrupt flag are cleared by reading the status register
  // and then reading the data register.
  // Example: Status = SCI1S1;
  //          Data = SCI1D;

}

ISR( TX)
{
  // NOTE: The routine should include the following actions to obtain
  //       correct functionality of the hardware.
  //
  // Error interrupt flags are cleared by reading the status register
  // and then reading the data register.
  // Example: Status = SCI1S1;
  //          Data = SCI1D;

}

*/

/*
** ===================================================================
**     Method      :  SCI3_Init (component Init_SCI)
**
**     Description :
**         This method initializes registers of the SCI module
**         according to this Peripheral Initialization Bean settings.
**         Call this method in user code to initialize the module.
**         By default, the method is called by PE automatically; see
**         "Call Init method" property of the bean for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void SCI3_Init(void)
{
  /* SCI1C2: TIE=0,TCIE=0,RIE=0,ILIE=0,TE=0,RE=0,RWU=0,SBK=0 */
  setReg8(SCI1C2, 0x00);               /* Disable the SCI1 module */ 
  (void)getReg8(SCI1S1);               /* Dummy read of the SCI1S1 register to clear flags */
  (void)getReg8(SCI1D);                /* Dummy read of the SCI1D register to clear flags */
  /* SCI1S2: LBKDIF=1,RXEDGIF=1,??=0,RXINV=0,RWUID=0,BRK13=0,LBKDE=0,RAF=0 */
  setReg8(SCI1S2, 0xC0);                
  /* SCI1BDH: LBKDIE=0,RXEDGIE=0,??=0,SBR12=0,SBR11=0,SBR10=0,SBR9=0,SBR8=0 */
  setReg8(SCI1BDH, 0x00);               
  /* SCI1BDL: SBR7=0,SBR6=1,SBR5=1,SBR4=0,SBR3=1,SBR2=0,SBR1=0,SBR0=0 */
  setReg8(SCI1BDL, 0x68);               
  /* SCI1C1: LOOPS=0,SCISWAI=0,RSRC=0,M=0,WAKE=0,ILT=0,PE=0,PT=0 */
  setReg8(SCI1C1, 0x00);                
  /* SCI1C3: R8=0,T8=0,TXDIR=1,TXINV=0,ORIE=1,NEIE=1,FEIE=1,PEIE=1 */
  setReg8(SCI1C3, 0x2F);                
  /* SCI1C2: TIE=0,TCIE=1,RIE=1,ILIE=0,TE=0,RE=0,RWU=0,SBK=0 */
  setReg8(SCI1C2, 0x60);                
}

/* END SCI3. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
